// This file is automatically generated at build-time
// to link all posts to the preact router.

import R from "preact-router"
import AR from "preact-async-route"
import { components as c } from "./components/MdxComponents"

const C=(m:any)=>()=><m.default components={c}/>

export const blog=(_:any)=>(<R>
<AR path="/blog/2021-08-04-vim-sets" getComponent={()=>import('../blog/2021-08-04-vim-sets.mdx').then(C)}/>
<AR path="/blog/2021-08-25-vim-1" getComponent={()=>import('../blog/2021-08-25-vim-1.mdx').then(C)}/>
<AR path="/blog/2021-08-25-vim-2" getComponent={()=>import('../blog/2021-08-25-vim-2.mdx').then(C)}/>
<AR path="/blog/2021-09-21-subtle-art-of-not-giving-an-f" getComponent={()=>import('../blog/2021-09-21-subtle-art-of-not-giving-an-f.mdx').then(C)}/>
<AR path="/blog/2021-09-23-making-myself-at-home-in-zsh" getComponent={()=>import('../blog/2021-09-23-making-myself-at-home-in-zsh.mdx').then(C)}/>
<AR path="/blog/2021-09-26-installing-arch" getComponent={()=>import('../blog/2021-09-26-installing-arch.mdx').then(C)}/>
<AR path="/blog/2021-09-27-after-installing-arch" getComponent={()=>import('../blog/2021-09-27-after-installing-arch.mdx').then(C)}/>
<AR path="/blog/2021-09-28-my-keyboard-1" getComponent={()=>import('../blog/2021-09-28-my-keyboard-1.mdx').then(C)}/>
<AR path="/blog/2021-09-29-reading" getComponent={()=>import('../blog/2021-09-29-reading.mdx').then(C)}/>
<AR path="/blog/2021-09-30-my-keyboard-2" getComponent={()=>import('../blog/2021-09-30-my-keyboard-2.mdx').then(C)}/>
<AR path="/blog/2021-10-01-vim-3" getComponent={()=>import('../blog/2021-10-01-vim-3.mdx').then(C)}/>
<AR path="/blog/2021-10-03-math-and-code" getComponent={()=>import('../blog/2021-10-03-math-and-code.mdx').then(C)}/>
<AR path="/blog/2021-10-04-analyzing-command-frequency" getComponent={()=>import('../blog/2021-10-04-analyzing-command-frequency.mdx').then(C)}/>
<AR path="/blog/2021-10-06-vim-4" getComponent={()=>import('../blog/2021-10-06-vim-4.mdx').then(C)}/>
<AR path="/blog/2022-01-01-managing-dotfiles" getComponent={()=>import('../blog/2022-01-01-managing-dotfiles.mdx').then(C)}/>
<AR path="/blog/2022-05-13-mysql-on-github-actions" getComponent={()=>import('../blog/2022-05-13-mysql-on-github-actions.mdx').then(C)}/>
<AR path="/blog/2022-12-22-modtree" getComponent={()=>import('../blog/2022-12-22-modtree.mdx').then(C)}/>
</R>)
export const projects=(_:any)=>(<R>
<AR path="/projects/gitnu" getComponent={()=>import('../projects/gitnu.mdx').then(C)}/>
<AR path="/projects/nvim-toggler" getComponent={()=>import('../projects/nvim-toggler.mdx').then(C)}/>
<AR path="/projects/prelude" getComponent={()=>import('../projects/prelude.mdx').then(C)}/>
</R>)