import { basename, extname, join } from 'path'
import { writeFileSync, readdirSync } from 'fs'
import matter from 'gray-matter'
import { compileSync } from '@mdx-js/mdx'
import { autolinkHeadings } from './autoLinkHeadings'

const PROJECT_ROOT = process.cwd()

type LoaderConfig = {
  [key: string]: { layout?: string }
}

const stripExtension = (filename: string) =>
  filename.slice(0, -extname(filename).length)

export function loadMdx(config: LoaderConfig) {
  const PREFIX = [
    '// This file is automatically generated at build-time',
    '// to link all posts to the preact router.',
    '',
    'import R from "preact-router"',
    'import AR from "preact-async-route"',
    'import { components as c } from "./components/MdxComponents"',
    '',
    'const C=(m:any)=>()=><m.default components={c}/>',
    '',
  ]

  const startRouter = (name: string) => `export const ${name}=(_:any)=>(<R>`
  const endRouter = () => '</R>)'

  const pre = (layout: string) =>
    `import { ${layout} as L } from "../src/layouts/all"`
  const post = (meta: string) =>
    `export default ({children}) => <L meta={${meta}}>{children}</L>`

  return {
    name: 'mdx-loader',

    /**
     * loads each individual post
     */
    transform(src: string, id: string) {
      if (!id.endsWith('.mdx')) return

      const tmp = Object.keys(config).filter((v) =>
        id.startsWith(join(PROJECT_ROOT, v))
      )
      if (tmp.length === 0) return
      const layout = config[tmp[0]].layout

      // extract frontmatter
      const { data: frontmatter, content: raw } = matter(src)

      // if no frontmatter is detected, cut short the parsing
      if (Object.keys(frontmatter).length === 0 || !layout)
        return compileSync(src).toString('utf8')

      const date = new Date(basename(id).split('-').slice(0, 3).join('-'))
      frontmatter.publishedAt = date

      const content =
        pre(layout) + '\n\n' + raw + '\n\n' + post(JSON.stringify(frontmatter))

      return {
        code: compileSync(content, {
          rehypePlugins: [autolinkHeadings],
          jsxImportSource: 'preact',
        }).toString('utf8'),
      }
    },

    /**
     * loads every post at once
     *
     * used to build routing and a summary database.
     */
    buildStart() {
      const lines = [...PREFIX]
      Object.keys(config).forEach((dir) => {
        const sourceDir = join(PROJECT_ROOT, dir)

        const files = readdirSync(sourceDir).filter((v) => v.endsWith('.mdx'))

        lines.push(startRouter(dir))

        files.forEach((relativePath) => {
          const endpoint = '/' + join(dir, relativePath)
          const impt = join('..', endpoint)
          const path = stripExtension(endpoint)
          lines.push(
            `<AR path="${path}" getComponent={()=>import('${impt}').then(C)}/>`
          )
        })

        lines.push(endRouter())
      })
      writeFileSync(join(PROJECT_ROOT, 'src/generated.tsx'), lines.join('\n'))
    },
  }
}
